spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message
      sensor-report: sensor_report
logging:
  level:
    org.springframework.amqp: DEBUG