server:
  port: 8081
  ssl:
    enabled: false


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      sensor-report: sensor_report
  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: userok
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect