version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11.0-management
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  spring-boot-app:
    image: your-spring-boot-image:latest  # Replace 'your-spring-boot-image' with the actual image name
    ports:
      - "8080:8081"  # Assuming your Spring Boot app runs on port 8080
    depends_on:
      - rabbitmq  # This ensures that RabbitMQ container is started before the Spring Boot app
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq  # Configuring Spring Boot to use RabbitMQ container
      SPRING_RABBITMQ_PORT: "5672"  # RabbitMQ default port
