server:
  port: 8084
  ssl:
    enabled: false

bot:
  name: kz_box_manager_bot
  token: 6782433661:AAH4NAJSTSlNIeE2my4vW4pGGTCSYZI34RY

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      callback-data-update: callback_data_update
      answer-message: answer_message
      answer-callback-query: answer_callback_query