server:
  port: 8085
  ssl:
    enabled: false

rest-service:
  url: http://localhost:8081/sensor

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      answer-message: answer_message
      callback-data-update: callback_data_update
      answer-callback-query: answer_callback_query
  datasource:
    url: jdbc:postgresql://localhost:5432/pogreb
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: true